name: multihack
region: nyc

services:
  - name: web
    github:
      repo: dimikot/multihack
      branch: main
      deploy_on_push: false
    build_command: npm install --include=dev && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    http_port: 3000
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: WORKOS_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: WORKOS_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NEXT_PUBLIC_APP_URL
        scope: RUN_AND_BUILD_TIME
        value: https://multihack.ondigitalocean.app
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: development
