name: multihack
region: nyc

services:
  - name: web
    github:
      repo: dimikot/multihack
      branch: main
      deploy_on_push: false
    build_command: npm install --include=dev
    run_command: NODE_ENV=development npm run dev
    environment_slug: node-js
    instance_size_slug: apps-d-4vcpu-8gb
    instance_count: 1
    http_port: 3000
